I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rpycodes/script.rpy", line 192, in script
    play sound "voice/stovvoice/ov.wav"
  File "renpy/common/000statements.rpy", line 298, in execute_play_sound
    loop = config.default_sound_loop
Exception: config.default_sound_loop is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rpycodes/script.rpy", line 192, in script
    play sound "voice/stovvoice/ov.wav"
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\ast.py", line 2232, in execute
    self.call("execute")
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 298, in execute_play_sound
    loop = config.default_sound_loop
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\defaultstore.py", line 97, in __getattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.default_sound_loop is not a known configuration variable.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
我们之间的爱恋化作少女来谋杀我 1.0
Sun Oct  9 13:59:53 2022
